### ISSUE TITLE
Table 1B

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#15]
| dataset | project | token | #voxels labeled | #different types | author |
| --- | --- | --- | --- | --- | --- |

let's discuss this and see how we feel.
note, i'm not sure how easy it will be to get "#voxels labeled", or # of different types

**Comment by j6k4m8** [comment]
partially fixed by https://github.com/neurodata/weekly-status-reports/issues/28

**Comment by jovo** [comment]
@j6k4m8 can you put the table into the document? it doesn't seem to be loading.
thanks, j

**Comment by jovo** [comment]
@j6k4m8 little help? tables do not seem to be loading in document.
@willgray

**Comment by j6k4m8** [comment]
My guess is this is an issue with how Jekyll is rendering the page — I'll
check it out today.

**Comment by jovo** [comment]
thanks

On Wed, Apr 20, 2016 at 10:55 AM, Jordan Matelsky notifications@github.com
wrote:

> My guess is this is an issue with how Jekyll is rendering the page — I'll
> check it out today.
> 
> On Wed, Apr 20, 2016 at 2:17 AM joshua vogelstein <
> notifications@github.com>
> wrote:
> 
> > @j6k4m8 https://github.com/j6k4m8 little help? tables do not seem to
> > be
> > loading in document.
> > @willgray https://github.com/willgray
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/neurodata/ocp-journal-paper/issues/15#issuecomment-212277477
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ocp-journal-paper/issues/15#issuecomment-212460606

## 

the glass is all full:  half water, half air.
neurodata.io
