### ISSUE TITLE
LIMS Data Entry

### ISSUE THREAD

**Issue by j6k4m8** [openconnectome/ocp-journal-paper#20]
These tokens have never had metadata set, but are listed as public tokens. I _guess_ could sit for a few days and write these up, but it'd be awesome if whoever's point-person for each of these tokens tackled a few of them.

<sup>
- ac3
- ac4
- ara_test
- cajal_demo
- codeneurochallenge0000
- codeneurochallenge0001
- codeneurochallenge0002
- codeneurochallenge0003
- codeneurochallenge0004
- codeneurochallenge0005
- codeneurochallenge0006
- codeneurochallenge0007
- codeneurochallenge0008
- codeneurochallenge0009
- codeneurochallenge0010
- codeneurochallenge0011
- codeneurochallenge0100
- codeneurochallenge0101
- codeneurochallenge0200
- codeneurochallenge0201
- codeneurochallenge0300
- cv_ac3_vesicle_2014
- flyemanno
- kasthuri11cc_ac3_vesicles
- kasthuri14s1colANNO
- kasthuri2015_ramon_v2
- kasthuri2015_ramon_v3
- kat11greencylinder
- kat11mito
- kat11mojocylinder
- kat11redcylinder
- kat11segments
- kat11synapses
- kat11vesicles
- kharris15apical_anno
- kharris15apical_axondendrite_catmaid
- kharris15apical_axon_catmaid
- kharris15apical_dendrite_catmaid
- kharris15apical_endosomal_catmaid
- kharris15apical_ersa_catmaid
- kharris15apical_gliasubcell_catmaid
- kharris15apical_glia_catmaid
- kharris15apical_mitomicro_catmaid
- kharris15apical_polyribo_catmaid
- kharris15apical_subcell_catmaid
- kharris15apical_synapse_catmaid
- kharris15oblique_anno
- kharris15oblique_axondendrite_catmaid
- kharris15oblique_axon_catmaid
- kharris15oblique_dendrite_catmaid
- kharris15oblique_gliasubcell_catmaid
- kharris15oblique_glia_catmaid
- kharris15oblique_subcell_catmaid
- kharris15oblique_synapse_catmaid
- kharris15spine_anno
- kharris15spine_axondendrite_catmaid
- kharris15spine_axon_catmaid
- kharris15spine_dendrite_catmaid
- kharris15spine_gliasubcell_catmaid
- kharris15spine_glia_catmaid
- kharris15spine_subcell_catmaid
- kharris15spine_synapse_catmaid
- mniatlas
- test_ramonify_public
- vesiclerf_example
- ZBrain
  </sup>

**Comment by jovo** [comment]
@Aeusman @kkutten1 @kunallillaney @alexbaden @willgray hack-lunch party next week?
