### ISSUE TITLE
Fix figures in /Results/store/

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#28]
@jovo, do you want plots of the time to R/W or throughput of the R/W?

@kunallillaney

**Comment by jovo** [comment]
Can you try time first and see how it looks?

On Friday, March 25, 2016, Jesse Leigh Patsolic notifications@github.com
wrote:

> @jovo https://github.com/jovo, do you want plots of the time to R/W or
> throughput of the R/W?
> 
> @kunallillaney https://github.com/kunallillaney
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ocp-journal-paper/issues/28

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by MrAE** [comment]
They have been updated and pushed. I don't like it.

**Comment by jovo** [comment]
those images don't look quite right.
time should be smaller with more threads, right?

On Sat, Mar 26, 2016 at 12:13 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> They have been updated and pushed. I don't like it.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ocp-journal-paper/issues/28#issuecomment-201702676

## 

the glass is all full:  half water, half air.
neurodata.io
