### ISSUE TITLE
To be sure we are aware of this webpage.

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#32]
@willgray @jovo Just double checking that we are aware of this [http://docs.neurodata.io/ndpaper2016/](http://docs.neurodata.io/ndpaper2016/)

**Comment by jovo** [comment]
yah, i made it.

On Tue, May 17, 2016 at 11:14 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @willgray https://github.com/willgray @jovo https://github.com/jovo
> Just double checking that we are aware of this
> http://docs.neurodata.io/ndpaper2016/
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndpaper2016/issues/32

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
