### ISSUE TITLE
greg & jesse todos for paper

### ISSUE THREAD

**Issue by gkiar** [openconnectome/ocp-journal-paper#34]
-  fig 1 (@MrAE)
  - [ ] replace content for panel **b** (@jovo @willgray to provide content, @MrAE to update figure)
  - [x] redo part **d** with new data from kunal
  - [x] remove graph panel **e**
  - [x] confirmation of the above (@jovo @willgray click if you agree)
- [x] fig 2 (@gkiar)
  - [x] adjust layout of panels
  - [x] consider replacement content for histogram panel (@willgray to advise)
  - [x] confirmation of the above (@jovo @willgray click if you agree)
- [x] fig 3 (@gkiar or @MrAE)
  - [x] await 3d figs from eric
  - [x] replace loni fig (@willgray to provide content)
  - [x] move kwame's ndreg figure to supplement
  - [x] confirmation of the above (@jovo @willgray click if you agree)
-  table 1 (@gkiar)
  - [x] remove from body of paper and place on the website
  - [x] add link to LANDING page in text of paper
  - [x] make abbreviated version of table for supplement
  - [x] confirmation of the above (@jovo @willgray click if you agree)
- [x] formatting (@gkiar and @MrAE)
  - [x] fix references
  - [x] fix markdown style links in paper (i.e. turn [*item*](url) into _item_ (url) and add refs where appropriate)
  - [x] fix all internal fig, section, and table links
  - [x] update captions to be consistent with updated figures
  - [x] remove all commented out graph content
  - [x] fix styling of words (e.g., NeuroData, ndstore)
  - [x] move all \jovo, \will, etc. to the new orange comment style stuff so that we can hide later
  - [x] remove annonotes in bibtex file
  - [x] fix bibtex file
  - [x] confirmation of the above (@jovo @willgray click if you agree)

**Comment by wrgr** [comment]
likely more to follow, but this is a wonderful advance!

**Comment by jovo** [comment]
we probably need a "big picture" fig 0 schematic,
explaining the whole system.
shall we draw one out on the board tomorrow?

**Comment by gkiar** [comment]
That's a great idea! gcal us with a time you want to work on it?

**Comment by wrgr** [comment]
cool.  i'm off campus - could do a call or send notes in advance (or just jump in later).

**Comment by alexbaden** [comment]
Kunal has a cool figure in the ndstore microns branch Readme. Maybe a good
starting point?

**Comment by jovo** [comment]
lunch?

On Wed, May 18, 2016 at 3:24 PM, Greg Kiar notifications@github.com wrote:

> That's a great idea! gcal us with a time you want to work on it?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndpaper/issues/34#issuecomment-220131524

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
maybe start a new issue for fig0, and upload that, and we can discuss?

On Wed, May 18, 2016 at 3:25 PM, Alex Baden notifications@github.com
wrote:

> Kunal has a cool figure in the ndstore microns branch Readme. Maybe a good
> starting point?
> On Wed, May 18, 2016 at 15:24 Greg Kiar notifications@github.com wrote:
> 
> > That's a great idea! gcal us with a time you want to work on it?
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/neurodata/ndpaper/issues/34#issuecomment-220131524
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndpaper/issues/34#issuecomment-220131928

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
everything but 1 thing done, which is already in a different issue, great job!
