### ISSUE TITLE
fig1 tile cache

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#35]
@jovo @willgray @gkiar the new data from Kunal is much noisier than the first set. I think we should go back to the first set.  Thoughts? 

It's updated on overleaf. 

Here are both of them side by side:
https://github.com/neurodata/ndpaper/commit/1b600a39d2fd3a95d8b01ed42d0c84a3516f9915#diff-0a4e82a1d1f31610865061c16784fb58

**Comment by MrAE** [comment]
@kunallillaney do you have an idea why the second set of data is noisier than the first?

**Comment by jovo** [comment]
@mrae they are on different scales, maybe look at them on the same scale?

On Thu, May 19, 2016 at 6:31 PM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> @kunallillaney https://github.com/kunallillaney do you have an idea why
> the second set of data is noisier than the first?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ndpaper/issues/35#issuecomment-220463873

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by kunallillaney** [comment]
It is not noisier. The cube prefetch size is 16 vs 64 earlier. This why they are spikes of tile fetch times more often.

**Comment by jovo** [comment]
@kunallillaney that is a good point.

@MrAE what if we only looked at the first 1000, or even 500 time points. 
we don't have 6000 pixels in that panel, which means that we are smoothing, 
and we are smoothing in some weird way, which might be aliasing in our brains, etc.

so, maybe figure out about how many pixels that would be on a regular monitor, 
and use # time points < # pixels?

**Comment by MrAE** [comment]
I selected the first 600 time points in trial No. 1. It's at least stable for the moment.
