### ISSUE TITLE
stuff for paper before showing it to people

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#36]
my prioritization scheme is below.
### basically required:
- [x] titles on all figure panels, fig 2 is a great example.  recall: titles provide _context_, not the labels of X and Y
- [x] organize supplement stuff, it all goes in webpage? or here?
- [x] figures _always_ inline, no matter what the journal says about doing that.
- [x] each paragraph should be able **one** thing.  so, when reading through, the quick fix is to break things up into more paragraphs.
- [x] structure: intro, methods (store, explore, process: note-removed "analyze"), results (image datasets, annotation datasets, neurocartography, spatial synapse), discussion.  in this org, i think ndio goes in "store", and ndparse goes in process (model refers to models of brain stuff, not image stuff).  i think this is a "right" organization for neuroscientists.
- [x] figure 5 removed, or has content, and/or table listing claims, or some such.
### would be my top priorities
- [x] table 2 lists amount of GB per row, add hildegrand data
- [x] table 1 lists amount of voxels labeled per row
- [x] compress TOC
- [x] logical flow of fig 4: 2D, 3D, parse.  it can be a column and long, needn't be "square".
- [x] it would be great to put green circles around all correct detections, and red circles around all errors.

@MrAE

**Comment by wrgr** [comment]
table 2 lists GB/row because it's image size
table 1 lists voxels/row because it's a count 

So we did it like that because they are different quantities.  Can homogenize but need your advice @jovo.  other things proceeding on track.

**Comment by jovo** [comment]
"table 2 lists GB/row because it's image size
table 1 lists voxels/row because it's a count"

that sounds great, but its not what i see?

On 5/24/16, William Gray notifications@github.com wrote:

> table 2 lists GB/row because it's image size
> table 1 lists voxels/row because it's a count
> 
> So we did it like that because they are different quantities. Can homogenize
> but need your advice @jovohttps://github.com/jovo. other things proceeding
> on track.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on
> GitHubhttps://github.com/neurodata/ndpaper/issues/36#issuecomment-221264530

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York

**Comment by wrgr** [comment]
@MrAE - can you take a look at restoring table 1 and 2 voxels and GB?  I know they are somewhere...leave things you can't find blank and I'll circle back.

**Comment by MrAE** [comment]
I'll check it out.

**Comment by MrAE** [comment]
I wasn't able to accomplish a whole lot.  Got a few in there.  Any pointers where all of this info resides?

**Comment by wrgr** [comment]
This is all in project info for each project/dataset.  I think we can make a nice curated list.  @j6k4m8, @gkiar - do we have a script for this?  If not, I can look into something.

**Comment by alexbaden** [comment]
I took a crack at table 2. I used the on-disk size of each DB for the size of the dataset. Items in Bold I wasn't sure about (either a weird value, or didn't know what the token was). 

| key | reference | datasets | modality | species | GB |
| --- | --- | --- | --- | --- | --- |
| OHN | Ohyama et al. Nature (2015) | 2 | EM | D. melanogaster | **Token??** |
| DBN | Bock et al. Nature (2011) | 1 | EM | M. musculus | 13,312 |
| WSD | Weiler et al. Scientific Data (2014) | 12 | AT | M. musculus | 141.2 |
| FLY | flycol | 1 | EM | D. melanogaster | **1.8** |
| ANM | Ahrens et al. Nature Methods (2013) | 1 | Ophys | D. rerio | **Token??** |
| BKC | Kasthuri et al. Cell (2015) | 4 | EM | M. musculus | 1021 |
| HSD | Harris et al. Scientific Data (2015) | 3 | EM | R. rattus | 9.4 |
| WRM | Worm Atlas | 3 | EM | C. elegans | **Token??** |
| TKN | Takemura et al. Nature (2013) | 1 | EM | D. melanogaster | 203 |
| XBN | Dyer et al. in review (2016) | 1 | XCT | M. musculus | **Token??** |
| LEE | Lee et al. (2016) | 1 | EM | M. musculus | **Token??** |
| **Total** |  |  |  |  | 14686.5 |

If someone can send me the missing tokens, I can get the rest of the sizes from disk.

Getting GV should be pretty easy, but probably best to write a quick and dirty script to do it. The GV will be an approximation, obtained by taking the number of cuboids at res 0 and multiplying by the cuboid size. A cuboid exists if there is even one voxel in a given region (e.g. kasthuri11 is 128 x 128 x 16). So, you could be off by a factor of 250,000 per cuboid, but for gigavoxels that should be reasonable? 

Not sure how to differentiate between machine annotation and hand annotation, except by token. Will probably need @willgray help there. 

Oh, and I made a spreadsheet to keep track of tokens and individual dataset sizes. Here's a viewing link: https://docs.google.com/spreadsheets/d/16ZROu82TqqqUfaw-DhWtOw-qR_hbNv9T01OshTOmptE/edit?usp=sharing 

Let me know if you want permission to edit.

**Comment by jovo** [comment]
thanks @alexbaden, really making progress now!

On Tuesday, May 31, 2016, Alex Baden notifications@github.com wrote:

> I took a crack at table 2. I used the on-disk size of each DB for the size
> of the dataset. Items in Bold I wasn't sure about (either a weird value, or
> didn't know what the token was).
> key reference datasets modality species GB
> OHN Ohyama et al. Nature (2015) 2 EM D. melanogaster _Token??_
> DBN Bock et al. Nature (2011) 1 EM M. musculus 13,312
> WSD Weiler et al. Scientific Data (2014) 12 AT M. musculus 141.2
> FLY flycol 1 EM D. melanogaster _1.8_
> ANM Ahrens et al. Nature Methods (2013) 1 Ophys D. rerio _Token??_
> BKC Kasthuri et al. Cell (2015) 4 EM M. musculus 1021
> HSD Harris et al. Scientific Data (2015) 3 EM R. rattus 9.4
> WRM Worm Atlas 3 EM C. elegans _Token??_
> TKN Takemura et al. Nature (2013) 1 EM D. melanogaster 203
> XBN Dyer et al. in review (2016) 1 XCT M. musculus _Token??_
> LEE Lee et al. (2016) 1 EM M. musculus _Token??_
> _Total_ 14686.5
> 
> If someone can send me the missing tokens, I can get the rest of the sizes
> from disk.
> 
> Getting GV should be pretty easy, but probably best to write a quick and
> dirty script to do it. The GV will be an approximation, obtained by taking
> the number of cuboids at res 0 and multiplying by the cuboid size. A cuboid
> exists if there is even one voxel in a given region (e.g. kasthuri11 is 128
> x 128 x 16). So, you could be off by a factor of 250,000 per cuboid, but
> for gigavoxels that should be reasonable?
> 
> Not sure how to differentiate between machine annotation and hand
> annotation, except by token. Will probably need @willgray
> https://github.com/willgray help there.
> 
> Oh, and I made a spreadsheet to keep track of tokens and individual
> dataset sizes. Here's a viewing link:
> https://docs.google.com/spreadsheets/d/16ZROu82TqqqUfaw-DhWtOw-qR_hbNv9T01OshTOmptE/edit?usp=sharing
> 
> Let me know if you want permission to edit.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-222830046,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcvKpDmK7jVxl1Tya_Z2gjVD6CX6Xks5qHKr2gaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
I suggest the following revised format for Table 2:

| reference | modality | species | _tokens_ (desc) | GB | GV |
| --- | --- | --- | --- | --- | --- |
| Harris et al. Scientific Data (2015) | EM | R. rattus | _kharris15apical_ (Apical Dendritic Segment), _kharris15oblique_ (Oblique Dendritic Segment), _kharris15spine_ (Spine Segment) | 9.4 | **XXX** |

Perhaps we can format tokens so line breaks appear between them?

I think it will be important for people to understand the concept of a token / how to get at some of this data. Certainly for reproducibility it would be helpful (e.g. histogram explorer). 

@willgray @jovo

**Comment by wrgr** [comment]
some thing like that would be great.  But i really can't do this reasonably unless someone dumps a token/channel list for me of public stuff.  If it's not reasonable to do, then Jesse and I will try to do with ndio, but 100x slower.

@kunallillaney

**Comment by jovo** [comment]
+1 to idea, and +2 to @alexbaden / @kunallillaney taking the lead on this
:-)

On Wednesday, June 1, 2016, William Gray notifications@github.com wrote:

> some thing like that would be great. But i really can't do this reasonably
> unless someone dumps a token/channel list for me of public stuff. If it's
> not reasonable to do, then Jesse and I will try to do with ndio, but 100x
> slower.
> 
> @kunallillaney https://github.com/kunallillaney
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-222853773,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcr4jiHJYzhm64LlwRFSvmptOQXyUks5qHMesgaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
Here's a link to all public tokens and channels: https://docs.google.com/spreadsheets/d/1lwjWgIiA1UF7U6XHALb5voTCHC3uwSUjn1o-wHFUlWw/edit?usp=sharing

Once we identify what we want to put in the paper, and how we want to organize it, I can convert that list into table 2.

I suggest we hide stuff we aren't interested in putting into the table. For example, for the first item (Ex3R43C2), I collapsed all channels except the first one, then bolded the token. In the table, we could collapse all the Ex tokens into the Weiler dataset, then list the tokens. 

I've sent edit links to Jesse, Will, and Jovo. Anyone else who wants one let me know!

**Comment by wrgr** [comment]
this is amazeballs.   I will curate this and report back.

**Comment by alexbaden** [comment]
Also, it was scripted -- so if we need different format or something along those lines, it's easy to change:

https://github.com/neurodata/ndstore/blob/master/util/publicTokensToCSV.py

**Comment by wrgr** [comment]
tables happening early next week - with @MrAE and @willgray!

**Comment by alexbaden** [comment]
I made draft versions of Table 1 (Images) and Table 2 (annotations) in Google Sheets. I failed to get them to overleaf... not sure how to use R to generate those tables. But sheets is fine for now, I think. 

https://docs.google.com/spreadsheets/d/1lwjWgIiA1UF7U6XHALb5voTCHC3uwSUjn1o-wHFUlWw/edit?usp=sharing

Let's ignore table 2 (annotations) and focus on table 1 (images). 

All the columns are self explanatory. We don't list channels because there are too many, and the user can list channels themselves once they have a token. The next column is a count of all cuboids for a given set of tokens (if a token contains image and annotation projects, just the image cuboids are included) **at resolution 0.** Next is the number of voxels in a cuboid. Then GigaVoxels in the dataset (numvoxels / 10^9). Data type tells us whether we're uint8 or uint16. Finally, we calculate the size of the data **at resolution 0** by multiplying `voxels * data type / 8` then convert the resulting bytes to GB. I think this gives a reasonable estimate. 

If we want the full data size, I can write a script to loop over resolutions and calculate a size for each resolution, based on the base resolution size (assume half the voxels die each time, right?) 

I also got the size of the db file from disk. It's fairly close. Note that the size of the DB file includes all resolutions, but also reflects compression. I would guess the db file and the calculated size varies in relation to how sparse the dataset is. 

I looked at the GB size for some sql dumps we have, and it's usually pretty close to the on-disk DB size. 

Decisions:
- [ ] Do we like table 1? If so, @alexbaden will finish off table 2 (annotations) 
- [ ] which GB metric do we use / show? 
- [ ] are we missing any datasets? 

Help Needed
- [ ] some TODOs in the doc for @willgray concerning xbrain, kasthuri, duplicates, etc -- touch base with @alexbaden 
- [ ] @jovo @willgray do we want to combine kasthuri11 under one or two references instead of the 4 / 5 it is now (in images)? What about in annotations? 
- [ ] @jovo -- reference, modality, species help 

It occurs to me, all the way at the end, that I may have switched the paper table order. Let's go with what I did for now (table 1 == images, table 2 == annotations) and we can change it later. 

Finally, this took me a long time so I made protected backup sheets. Please don't edit them, edit the current table 1 and table 2 sheets! Thanks :-)

**Comment by jovo** [comment]
-  i love Table 1.  i italicized the columns that i think go in the paper.  more specifically, for the table in the main paper (maybe something more elaborate goes in the appendix, each pub gets a single row.  there is no need to list tokens (as you mention, they can find them). i added a row "# Tokens / Channels / Time-Steps", 
- bloss and codeneuro were missing. as was codeneuro.
  - [ ] @Aeusman is codeneuro ingested properly now? if so, can you provide a link to the viz project? if not, can you make a new issue for yourself with a milestone of monday?
- should kristina public? i don't recall? 
  - [ ] @alexbaden can you find out today. and report back?
- i added all references & modalities,  
  - [ ] @willgray please add species & then check this box by monday?
- and what you labeled Table 1 should be Table 1 in the figure.
  - [x] @alexbaden let me know when you want me to look at table 2

👬

**Comment by alexbaden** [comment]
Sounds good. I think there's a good argument for listing tokens though -- between Will and myself, we weren't able to identify the tokens for all the publications you listed. Finishing the data pull turns out to be a terrible airplane activity, but I have 4 hours in Dallas so I'm sure I can take care of it then...

**Comment by jovo** [comment]
fair enough, if we want to give people a "collection" --> "token" map, 
let's make another table for that.
the purpose of this table is to demonstrate the depth and breadth of our data.

NB: this is why dean added a layer, and why i asked jordan in ndlims to create a field called "publication", so that we could search by publication.  eventually, i think our data model will have to mature to accommodate easily finding tokens associated with publications, but not before we submit this publication :)

**Comment by alexbaden** [comment]
Word.

**Comment by Aeusman** [comment]
@jovo CodeNeuro data cannot be ingested as timeseries data, the way the back end works right now is not able to handle the ingest of single slice timeseries data. @kunallillaney can explain more

**Comment by jovo** [comment]
@Aeusman everything is possible!  
i think you are trying to say that ingesting single slice time-series data might require @kunallillaney to add some functionality to ndstore?

some of the codeneuro data is multi-slice time-series, so i don't see why those datasets would be problematic?

**Comment by Aeusman** [comment]
@jovo I'm not sure, it was my understanding having spoken to him that this would require a re-write of a number of things and so may be a large issue to tackle. 

I am unclear which codeneuro datasets are multi-slice time series, as their site http://datasets.codeneuro.org/ is down. I tried emailing them several times, but to no avail and there is no metadata in the files that indicates which are and aren't multi-slice.

**Comment by jovo** [comment]
ah, they have a gitter chatroom: https://gitter.im/orgs/codeneuro/rooms
and if that doesn't work, you can email jeremy freeman directly.

On Wed, Jun 8, 2016 at 6:30 PM, Alex Eusman notifications@github.com
wrote:

> @jovo https://github.com/jovo I'm not sure, it was my understanding
> having spoken to him that this would require a re-write of a number of
> things and so may be a large issue to tackle.
> 
> I am unclear which codeneuro datasets are multi-slice time series, as
> their site http://datasets.codeneuro.org/ is down. I tried emailing them
> several times, but to no avail and there is no metadata in the files that
> indicates which are and aren't multi-slice.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-224647717,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjchBTjZcHTsGMr8UkSH5djpD8XIRkks5qJu4hgaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by Aeusman** [comment]
@jovo I messaged jeremy on gitter, will let you know when I hear back.

**Comment by Aeusman** [comment]
@jovo According to him all of the datasets are a single slice over time

**Comment by jovo** [comment]
@alexbaden the only remaining sub-tasks for this issue are the tables, and my understanding is that we'll have working drafts of them this week, and you are in charge of that, and will continue tasking people as appropriate to give you what you need, but will have in the draft a version of the tables that is "presentable" by the end of the week?

**Comment by alexbaden** [comment]
Yup. The draft of table 1 is done for all existing tokens, minus a few species (@willgray?). I will try and wrangle a few more tokens on campus today, and also get a draft of table 2.

**Comment by jovo** [comment]
oh great, done = "in overleaf"?

On Thu, Jun 9, 2016 at 2:33 PM, Alex Baden notifications@github.com wrote:

> Yup. The draft of table 1 is done for all existing tokens, minus a few
> species (@willgray https://github.com/willgray?). I will try and
> wrangle a few more tokens on campus today, and also get a draft of table 2.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-224880824,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcj9RLuHZWrLnSyWcwGu67CRCzVdpks5qKAgGgaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
No -- I will do that today.

Alex

**Comment by wrgr** [comment]
alex - will get you feedback today.  hopefully this am.

**Comment by alexbaden** [comment]
Draft of table 1 and table 2 now exist in the google sheet.

@jovo  -- can you take a look at table 2? I italicized what I thought you might want. Let me know what headers are missing. 

@willgray -- I still need a few items from you. Mainly parsing the tokens in the xbrain2016 project as machine or hand, as well a clarification on ac3/ac4 (I believe ac3 and ac4 are just hand annotations?)

**Comment by jovo** [comment]
@alexbaden - this is awesome.
i filled in some blanks in table 2.
i think the columns that make the most sense are:
reference, method, # GV, # RAMON objects.
if that last one is difficult to obtain,
let's put the table in the draft without it for now?

On Thu, Jun 9, 2016 at 7:10 PM, Alex Baden notifications@github.com wrote:

> Draft of table 1 and table 2 now exist in the google sheet.
> 
> @jovo https://github.com/jovo -- can you take a look at table 2? I
> italicized what I thought you might want. Let me know what headers are
> missing.
> 
> @willgray https://github.com/willgray -- I still need a few items from
> you. Mainly parsing the tokens in the xbrain2016 project as machine or
> hand, as well a clarification on ac3/ac4 (I believe ac3 and ac4 are just
> hand annotations?)
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-224962261,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcmIM9ukib5Hh1NYJrkvQcLAJsXBcks5qKEjqgaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
will do this afternoon.  i'm out tomorrow.  let's shoot for replacing the tables in the paper with these by end of day?  might need @MrAE to run his script, or might be easy to convert to latex?   

Goal is working-working on the paper.

**Comment by wrgr** [comment]
Did everything I could, including looking up all species.  RAMON is premature/difficult for now.  I like Joshua's columns I think.  Nice and clean.  I think the full columns are really good to preserve and should be online.

We're also making a table 3 @jovo - which answers questions like "how much data do we have" "how much public" "how much manual" etc.  Either for the paper or to draw from to fill in all the XXX and YYYs.

**Comment by jovo** [comment]
all great!
table 3 of course after table 1 & 2...

On Thu, Jun 9, 2016 at 8:44 PM, William Gray notifications@github.com
wrote:

> Did everything I could, including looking up all species. RAMON is
> premature/difficult for now. I like Joshua's columns I think. Nice and
> clean. I think the full columns are really good to preserve and should be
> online.
> 
> We're also making a table 3 @jovo https://github.com/jovo - which
> answers questions like "how much data do we have" "how much public" "how
> much manual" etc. Either for the paper or to draw from to fill in all the
> XXX and YYYs.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/36#issuecomment-224989097,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjckqBYm_fOiIz8miirEzBO_sOVGB6ks5qKF8AgaJpZM4Ijo02
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
that's a hilarious comment.  :)  table 3 to follow next week, probably @alexbaden - goal for the moment is just 1 and 2.  3 is a collapsing of some of the columns that aren't part of the main T1 and T2.  :)

**Comment by wrgr** [comment]
w00t for now

**Comment by jovo** [comment]
💑
