### ISSUE TITLE
XXX's and YYY's 

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#39]
There are a bunch of places in the paper with either `XXX` or `YYY` as place holders for information.

@willgray @jovo @gkiar

**Comment by will** [comment]
No ZZZ though I hope

**Comment by MrAE** [comment]
Sorry, wrong Will

**Comment by wrgr** [comment]
done.  some things are encapsulated in TODOs, mostly things that will fall out of table 3

**Comment by jovo** [comment]
💑
