### ISSUE TITLE
fig naming convention

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#40]
let's choose a convention and stick with it, and let's be sure to save each panel separately as well as together (because we'll use the separate ones for talks and stuff).

for example, store_vol_read, store_vol_write, ..., store (for the whole thing, if you generate it in lucidchart or something for now).

i tend to not like calling things by figure number/letter because they often change before submission, 
but the content will be clear.

**Comment by MrAE** [comment]
Good idea.

**Comment by wrgr** [comment]
let's call them store, explore, parse, cartography, synapse

volread, volwrite

If you can avoid underscores, that keeps things from breaking (I have trouble with some packages interacting poorly with underscores unless you explicitly escape them...)

@MrAE - this is you!  Let's also remove old figures - ones that we like can go into git somewhere, but generally these just get better everytime.  Repo is getting big.

**Comment by MrAE** [comment]
I renamed a bunch in overleaf already.  I replaced underscores with "-" to enhance efficiency when typing them out as you don't have to hold down the shift key.

**Comment by wrgr** [comment]
cool - what's your convention?  I'll follow it.  Also, can we kill the old figs tomorrow or soon?

**Comment by MrAE** [comment]
- `store-<description>.<file-extension>`
- `explore-<description>.<file-extension>`
- `parse-<description>.<file-extension>` 
- `extneuro-<description>.<file-extension>`
- `spdist-<description>.<file-extension>`

**Comment by wrgr** [comment]
beautiful  :)

**Comment by MrAE** [comment]
I'll look through and delete unused figures tomorrow.

**Comment by jovo** [comment]
so, all the figs are now in the ndpaper repo,
or the overleaf repo?

On Fri, Jun 3, 2016 at 6:04 AM, Jesse Leigh Patsolic <
notifications@github.com> wrote:

> I'll look through and delete unused figures tomorrow.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/40#issuecomment-223485864,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcrJYxrRD6zbOpYo1uNsDzOdqOc4Qks5qH6fFgaJpZM4IpQX_
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
bump?

**Comment by MrAE** [comment]
They are in overleaf so far as I know.
