### ISSUE TITLE
stuff required before sending to nature editor

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#41]
- [x] complete reproducability explore pages @alexbaden 
- [ ] complete reproducability store pages @kunallillaney 
- [x] @kunallillaney put simplified schematic of entire backend in lucidchart & invite jovo (showing ndstore, S3, ndblaze, ndtilecache, and ndviz on appropriate hardware).
- [ ] finish use case technical content @willgray 
- [ ] provide feedback and edit as appropriate @jovo

fyi @randalburns @MrAE @gkiar

**Comment by alexbaden** [comment]
First attempt at the Explore reproducibility page: http://docs.neurodata.io/nddocs/ndpaper2016/explore.html 

Waiting for feedback! 👍

**Comment by jovo** [comment]
is a great start!

i'll let @willgray take the first shot at feedback.

one "obvious" omission: how do we use/get to the histogram explorer?

thanks!

On Tuesday, May 31, 2016, Alex Baden notifications@github.com wrote:

> First attempt at the Explore reproducibility page:
> http://docs.neurodata.io/nddocs/ndpaper2016/explore.html
> 
> Waiting for feedback! 👍
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/41#issuecomment-222820700,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcmal9rolzzOq7Vht_ckDpW6ZATjhks5qHKLngaJpZM4Ipg_3
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
will do tonight or tomorrow latest  :)

**Comment by alexbaden** [comment]
Doh! Histogram explorer section added. I need to generate a histogram for the 16-bit example. That process has already been started, when it finishes I will push an update.

**Comment by jovo** [comment]
better!

but i don't understand how the buttons work,
or, perhaps they do not work?

On Wednesday, June 1, 2016, Alex Baden notifications@github.com wrote:

> Doh! Histogram explorer section added. I need to generate a histogram for
> the 16-bit example. That process has already been started, when it finishes
> I will push an update.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/41#issuecomment-222859778,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcmMi14NekQVw5BH0FRmNIVYjdLcNks5qHNDwgaJpZM4Ipg_3
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
Apply Window to Image will only work if the image is from a 16-bit dataset. kharris15apical / em is 8 bit, so the windowing / image features don't work. The other buttons still work, though -- copy to min, copy to max (though they aren't useful without 16 bit) and the precentile slider.

**Comment by jovo** [comment]
i see.
documentation should clarify.

your reproducible text is great, though much of it really belongs in the
documentation i think?
in particular, everything other than how to reproduce the figure?

On Wednesday, June 1, 2016, Alex Baden notifications@github.com wrote:

> Apply Window to Image will only work if the image is from a 16-bit
> dataset. kharris15apical / em is 8 bit, so the windowing / image features
> don't work. The other buttons still work, though -- copy to min, copy to
> max (though they aren't useful without 16 bit) and the precentile slider.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/41#issuecomment-223014330,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcozlC7Y2J9ZlA1Fg9aOFXTl_XuVCks5qHZo0gaJpZM4Ipg_3
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
moving along with this.  feedback mostly happening one-one but major things will post here.

**Comment by wrgr** [comment]
use cases moving along.  Lots of stuff today.  More to come tomorrow.  :)
Kunal got us an awesome fig @MrAE  is going to insert!

**Comment by MrAE** [comment]
Where is the location of the above mentioned figure?

**Comment by wrgr** [comment]
https://github.com/neurodata/ndstore/blob/microns/docs/images/neurodata_cluster.png

:)

**Comment by MrAE** [comment]
I'll fit that in tomorrow.

**Comment by kunallillaney** [comment]
@MrAE This is a longer conversation with @jovo which we can move to an email. We did not run any tests with S3 on the benchmarks. So not sure if it makes sense to include S3 in the figure or talk about it.

**Comment by jovo** [comment]
- [x] "In addition to the data exhibited in Figure 2, we wish to highlight the following published 8-bit EM Datasets:" and the following table i think are not appropriate in reproducability appendix for the paper. but that table is great, i recommend moving it to ndviz documentation, and maybe offering a link here.
- [x] "Public tokens and channels are available in Table 1, Table 2, and supplementary material." probably not true
- [x] "16-bit Datasets" also not appropriate for reproducability, please move to ndviz docs
- [x] "However, only a small number of paint datasets include RAMON metadata." unnecessary to say in reproducability, please remove.
- [x] "The following projects from the Images table also include annotation data:"   also unnecessary in reproducability, please move to docs.
- [x] "Matrices" etc: please remove.

after that, i think explore reproducability is done!

**Comment by wrgr** [comment]
@alexbaden - hold on moving these until we find a good place - if you have one, let me know.

**Comment by wrgr** [comment]
Ok - @alexbaden - can you move the data to http://docs.neurodata.io/nddocs/ndpaper2016/data.html (corresponding md file).  Anything you prefer in ndviz docs, fine by me, but I think most of this is useful for the paper.  Easy to rearrange later.  And either way, once you do this, we can close the issue!

**Comment by alexbaden** [comment]
Moved. Explore section should be done. @jovo, take a look and lemme know? 

PS: I moved histogram to tutorials. It doesn't have a good home. Once this madness is done, we can find it a good home.

**Comment by wrgr** [comment]
i think this subtask is now complete!  @jovo - do a quick review or store and see what you think?

**Comment by jovo** [comment]
💑
