### ISSUE TITLE
fig:Parse-object-detection

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#42]
Regarding fig:parse (i):

When printed the text size is not big enough. Can you send shorter descriptions?

Otherwise, just making the text larger will make the figure wider than the others in the panel.

@will @jovo @gkiar

**Comment by wrgr** [comment]
@MrAE:  figure is updated here in the lucid chart:  https://www.lucidchart.com/documents/edit/073fd4e1-2ce5-401b-bf92-480d69111ad6/13

**Comment by wrgr** [comment]
nevermind - i got it!  updated - great suggestion @MrAE - wayyyyyy better.
