### ISSUE TITLE
Markram 15 citation info

### ISSUE THREAD

**Issue by MrAE** [openconnectome/ocp-journal-paper#43]
Link for Markram 15, so I can create the citation.

@willgray @jovo @greg

**Comment by jovo** [comment]
Reconstruction and Simulation of Neocortical Microcircuitry

On Tuesday, May 31, 2016, Jesse Leigh Patsolic notifications@github.com
wrote:

> Link for Markram 15, so I can create the citation.
> 
> @willgray https://github.com/willgray @jovo https://github.com/jovo
> @greg https://github.com/greg
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/43, or mute the thread
> https://github.com/notifications/unsubscribe/AACjcvtyecE6QqArVSEcYW2HIkONONqzks5qHJ8IgaJpZM4Iq8ct
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by MrAE** [comment]
Thanks
