### ISSUE TITLE
Will Nature Paper Issues

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#45]
refactoring issues by people...
- [x] Table 1 content
- [x] Table 2 content
- [x] Table overview rough cut text
- [x] Move paper back to github (everyone else seems to like that better and makes more sense with current structure...)

**Comment by wrgr** [comment]
table content being fixed this week

**Comment by jovo** [comment]
@willgray you are the assignee here?
we can make the overleaf thing a submodule in the github repo, 
so that you can have your cake and eat it too?

**Comment by wrgr** [comment]
making one of these issues for all of us...this is mine!  do you know how to do the overleaf thingy?

**Comment by jovo** [comment]
https://www.overleaf.com/blog/195-new-collaborate-online-and-offline-with-overleaf-and-git-beta#.V1M9SZN97sk

https://www.overleaf.com/help/233-how-do-i-connect-an-overleaf-project-with-a-repo-on-github#.V1M9Y5N97sk

**Comment by jovo** [comment]
@willgray confused by this issue. @alexbaden is doing tables? are you moving back to github this week? please clarify.

**Comment by wrgr** [comment]
Tables are indeed my responsibility.  Alex has tasks and is doing great - we should have new drafts of tables this week, maybe today.

This week was dynamic, so wasn't as captured in github as other weeks.  If you need a summary, please ask.  Will reassess paper early next week and make issues.  Sooner if you need them.  Note issues are now per person for clarity, not per topic for this repo.

**Comment by wrgr** [comment]
done for this version.  new issues for next week.

**Comment by jovo** [comment]
👬
