### ISSUE TITLE
reference point

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#47]
for the store numbers, people have no reference point, meaning they won't know what is "good".
i realize that all reference points we might be able to provide will likely be partially misleading,
because we are proposing a fundamentally different computing model,
nonetheless, without a reference point, they will have no idea how awesome our performance is.

here is one example reference point, i imagine you guys can think of better ones: 
- ingest throughput: if data of size {x,y,z} were already in dropbox, what is the throughput with which somebody at JHU get it from dropbox onto _some_ machine to do analysis on?
- download volume reference point: similarly, if data of size {x,y,z} were on some machine, what is the throughput to get it into dropbox? 
- quoting the average download/upload in the US?
- or the average download/upload speed at universities for a single machine?

@kunallillaney @willgray please discuss and come up with something?  doesn't have to be perfect, but we should a pair of numbers as a reference point.

**Comment by wrgr** [comment]
@jovo - call in this afternoon and we'll talk?

the win in terms of speed is in cuboids not in pulling whole data.  To simulate this is a fairly involved thing...but doable.  Want to make sure we are approaching correctly.

**Comment by jovo** [comment]
think of the simplest thing.  it doesn't involve writing any code.
no need to discuss.  this is an exercise for you guys.
think of the simplest thing, put your best guess in the comments here, 
no need to modify text, _definitely_ no need for code....SIMPLE SIMPLE SIMPLE.
it doesn't matter if we win. all that matters is a simple point of reference.
- how long to copy data from one machine to another on a network drive is a fine reference.

put ANY number in here, and that is progress....

**Comment by wrgr** [comment]
42

**Comment by jovo** [comment]
that is progress!!!!

next: i need a unit for it to be meaningful.

baby steps....

On Mon, Jun 6, 2016 at 7:29 PM, William Gray notifications@github.com
wrote:

> 42
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/47#issuecomment-224028619,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcrw23ouXOq359BETR72IxjplR33kks5qJFjvgaJpZM4IvCAM
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
newtons

**Comment by jovo** [comment]
ok, a little more useful one.
eg, GB/s.

now that we have a number and unit, we need context.

we get  42 GB/s when doing _____

you guys fill in the blank.

this is a real exercise. you guys need to learn how to just do _something_, and then we can fix it.

perfect is the enemy....

**Comment by jovo** [comment]
c'mon.....

**Comment by wrgr** [comment]
http://blog.takipi.com/amazon-ec2-2015-benchmark-testing-speeds-between-aws-ec2-and-s3-regions/

Reports 40 seconds/GB, or 25MB/second when transferring between ec2 and s3 in the same region.
- This is for 10MB  files...so overhead maybe misleading.

Benchmarks for cloud services in general are a bit flaky.  But here's a start.

**Comment by jovo** [comment]
this is great!!!!
