### ISSUE TITLE
Table Formatting

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#51]
Tables are looking great!
- [x] Add citations for each reference in table 1 and 2 as appropriate
- [x] I think leave Time blank rather than NA
- [x] add table captions
- [x] Look in old version of tables for missing rows that we overlooked in the latest scrub
- [x] remove GB, data bit depth and resolution from image table
- [x] Remove resolution column
- [x] remove GB from table 1

Goal at the end of this is table 1, table 1a (more cols), table 2, table 2a, table 3, where 'a' versions go on website and main tables in paper.

@alexbaden

**Comment by jovo** [comment]
here are my first thoughts on the table:
1. this is AWESOME!
2.  a lot of whitespace could easily be removed without removing any columns.  consider:
   - [x] replacing reference with just the last name of the first author
   - [x] make the top row 2 lines, and put all units on the 2nd line
   - [x] change image size to '#voxels'
   - [x] put 'data type' and 'bit depth' on different lines, or just use 'bit depth'
   - [x] replace N/A with '1', when it is anatomical data
   - [x] shorten "#Resolutions" to "#Res"
   - [x] just use "GB" for the last col.
3. the caption can explain all abbreviations, and provide citations.

i would do this stuff, and then check whether the table fits, and if not, we can iterate again.

**Comment by MrAE** [comment]
I'm working on this now.  ⏳

**Comment by alexbaden** [comment]
I made all Jovo's changes in Google sheets. I will get a copy to @MrAE after I add in the CLARITY datasets.

**Comment by alexbaden** [comment]
As far as deal with object count goes, there are only two ramonified datasets (the two with object counts). So, we can set all the rest to 0, leave them blank (as it is now), or remove object count entirely. We could try and write a script to give us all the unique IDs in an annotation dataset, but that involves looping over all cuboids and creating a list -- very time consuming. A possibility for revision, but not likely in the next week or so.

**Comment by MrAE** [comment]
I changed some things and just pushed to the paper repo.  I went off of the previous versions of the google sheets and changed after in R and LaTeX.  Let me know how they look. 👇 @jovo @willgray

**Comment by jovo** [comment]
### table 1
- [x] clarity and kristina are both mouse
- [x] CLARITY reference is kwame's paper
- [x] i don't love "#Data".  in our data model, it is called "Projects", right?
- [x] maybe replace "X / Y" with "X, Y" (note i removed a space)? 
- [x] caption must define all acronyms (not genus), and state # of different references, total # of GV, and total #Data. 
- [x] sort by modality/resolution, eg EM, AT, Ophys, XCT, LM, CLARITY, MR

### table 2
- [ ] @willgray guess # of objects
- [ ] @alexbaden vesicle is a proper @willgray citation
- [ ] @alexbaden Raju should be kwame's paper, and they are machine i would say, though perhaps @willgray might disagree?

**Comment by alexbaden** [comment]
Jovo and I did a final-ish table 1 review this evening. I think we are set! 

@willgray and I will continue to work on table 2. I need a resolution of the # of objects, at minimum. 

Once the paper versions are finalized I think we should close this, and open a new one for the online version.

**Comment by jovo** [comment]
- [ ] add full table versions to webpage even as we trim columns for paper
  is not a priority this week, so i removed.
- [ ] deal with object count
  i moved to your task, so we have just 1 task per person per week.
