### ISSUE TITLE
Reproducibility for Store

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#54]
@jovo - this was open on another issue that was closed, but simpler here and explicit and external.

**Comment by jovo** [comment]
great!
@kunallillaney there are some todo's in the paper as well. i think those are a higher priority than reproducability.

**Comment by jovo** [comment]
@willgray & @kunallillaney please discuss and add appropriate milestone.

**Comment by kunallillaney** [comment]
The reproducibilityexists [here](https://github.com/neurodata/ndpaper/blob/master/store/store.md). can you please be more specific on what you want to update?

**Comment by jovo** [comment]
it looks really great.
for those benchmarks, its not clear where we run that code, just from any machine?
and then just add the line for running to code to make the fig once @MrAE makes it.

@kunallillaney let me know if you have any questions on the main text comments.

**Comment by wrgr** [comment]
My hope here is to knock out reproducibility because Kunal has done a great job and it's just in need of the updates above and any other @jovo review.  And we can move on to other issues!

**Comment by kunallillaney** [comment]
@jovo I updated it and also left a stub in there for @MrAE to fill in the link to the R script.

**Comment by jovo** [comment]
is [this](http://docs.neurodata.io/nddocs/ndpaper2016/store.html) the right link for store?
if so, it got reverted?

**Comment by wrgr** [comment]
Can I get a status update here @kunallillaney ?  I think the right goal for you this week is the text updates for the paper, but if this is still open, then I will delay that one so you can focus on knocking this out.

**Comment by kunallillaney** [comment]
The text is [here](https://github.com/neurodata/ndpaper/blob/master/store/store.md). @jovo is ether looking at the wrong place or someone setup the repo wrong.

**Comment by MrAE** [comment]
All of the website/landing page stuff for store was setup [here](https://github.com/neurodata/nddocs/blob/gh-pages/ndpaper2016/store.md)

**Comment by kunallillaney** [comment]
@MrAE I have a slack message from @willgray telling me to copy it over to this repo in the store folder. If things were changes after that then I was not informed. :)

**Comment by MrAE** [comment]
So then, @willgray where do you want it/where is it supposed to go?

**Comment by alexbaden** [comment]
All of the links on the ndpaper landing page (http://docs.neurodata.io/ndpaper/) point to files in the ndpaper directory in the docs repo. 

So the path to store that is currently linked from the landing page is: `http://docs.neurodata.io/nddocs/ndpaper2016/store.html`
which would correspond to 
`ndpaper2016/store.md` in the `nddocs` repo (https://github.com/neurodata/nddocs/blob/gh-pages/ndpaper2016/store.md) 

I'm not sure why it was setup this way, but for the explore stuff, the current version is in the ndpaper2016 dir in nddocs, not the explore.md file in explore dir ndpaper repo. Confused yet? :-)

**Comment by wrgr** [comment]
Paper stuff should be in paper repo I think?  Apologies if I've been unclear!

**Comment by jovo** [comment]
i think the way it is set up store.md goes in the gh-pages branch of the
ndpaper repo.

On Mon, Jun 13, 2016 at 5:54 PM, William Gray notifications@github.com
wrote:

> Paper stuff should be in paper repo I think? Apologies if I've been
> unclear!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/54#issuecomment-225624515,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcvwrfirhNCCCF6QpqkDZRgJ1_hA2ks5qLX1NgaJpZM4IykmA
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
ok, closing this issue, https://github.com/neurodata/ndpaper/issues/57 specifies that @willgray will tell @kunallillaney the right location.
