### ISSUE TITLE
Store Text TODOs

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#57]
Add text / respond to comments in store section of paper.

**Comment by kunallillaney** [comment]
- [x] Codeneuro TODO
- [x] Read through ingest and blaze
- [x] Update ingest section
- [x] Update propagate section

**Comment by kunallillaney** [comment]
@jovo I did all the TODO's in the store.tex section. I should summarize the ndblaze section better because it seems quite a bit. Let's talk tomorrow on this and I will do it immediately after that.
- [ ] Summarize ndblaze section

**Comment by kunallillaney** [comment]
@willgray Can you please wrap up your TODO in this section. I am still confused which is the correct location.

**Comment by jovo** [comment]
@kunallillaney i moved @willgray 's task to his issue.
of note, store.tex wasn't compiling, i fixed it.
you got the content in for ndblaze, so i'm closing this issue, we can make a new one for revising text!
