### ISSUE TITLE
alex embettering paper

### ISSUE THREAD

**Issue by alexbaden** [openconnectome/ocp-journal-paper#61]
- [x] update fig0 caption
- [x] update table2 caption and 'vesicle' entry
- [x] update table 2 w/ @willgray estimates 
- [x] table 1 caption: define modality acronyms. and 
- [x] period missing at end of caption.
- [x] generate reproducability doc for clarity ingest, and histogram stuff. moved to #67

**Comment by wrgr** [comment]
table 2 is really confusing to me (e.g., kasthuri11 data has many projects with annotations - there's no reasonable way anyone could find out what is available with this table).  What do you think about listing tokens (not projects or channels) and describing?

e.g., vesicle has a paper reference, is based on kasthuri data, but the result is machine vision annos
kasthuri2015_ramon_v4 is a token contaiing a set of channels corresponding to hand annotations
something_gala_v1 is a token corresponding to machine annotations
 etc.

**Comment by jovo** [comment]
do you mean table 2?
the point is to tell people that we have annotations, not provide a map.
if you want to provide a map, you are welcome to, after we do all the other
results.

On Wed, Jun 15, 2016 at 11:04 PM, William Gray notifications@github.com
wrote:

> figure 2 is really confusing to me (e.g., kasthuri11 data has many
> projects with annotations - there's no reasonable way anyone could find out
> what is available with this table). What do you think about listing tokens
> (not projects or channels) and describing?
> 
> e.g., vesicle has a paper reference, is based on kasthuri data, but the
> result is machine vision annos
> kasthuri2015_ramon_v4 is a token contaiing a set of channels corresponding
> to hand annotations
> something_gala_v1 is a token corresponding to machine annotations
> etc.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/61#issuecomment-226376878,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjch4WauduMcDu-orcLtNouqZyzqOPks5qML0xgaJpZM4I06g4
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
Once the paper is submitted we can clean up the website / public projects page / etc. We also need to go through our public data, decide where it is going to live long term (I vote not datascope), and move it there. When we move it, we should convert to the new format so things are uniform (e.g. kasthuri11 is a project with a series of channels). We can always create tokens to match the existing data as closely as possible. A discussion for another day... 

Another discussion for another day: in the future, our public servers should only host public projects. Anything else should live somewhere else until it's ready to be made public, then migrated. Part of the problem is we have literally hundreds of projects on datascope, and nobody knows what they all are.

**Comment by wrgr** [comment]
Sure - it's hard for me to estimate ramon objects without knowing all the underlying stuff. 
Also gives credit to image dataset rather than analysis people - maybe we just list multiple refs for each anno paper?  Based on what I know as a first cut:
- kasthuri machine - O(100000)
- takemura machine - O(100000)
- harris hand - O(1000)
- vesicle (subset of kasthuri?) - O(100000)
- dyer (xbrain? hand) - O(1000)
- bhatla (worm, right?) - O(1000), to be confirmed
- kutten (clarity mouse, right?) - O(10000), to be confirmed

**Comment by wrgr** [comment]
@alexbaden - agree in general - one thing to consider is that people will use reference datasets to publish other papers, and we may not want people adding new channels to existing published projects (e.g., 1 public project = 1 paper, sort of).  Or a schema update would solve.  But for another day...

**Comment by alexbaden** [comment]
@jovo For clarity reproducibility and histogram stuff, the clarity "ingest" I am doing is fundamentally not [easily] reproducible. I'm dumping brains from dsp in the old format, converting to the new format (manually, by disabling foreign key checks and running custom SQL queries), and re-loading the data to match our new channels format. Even if you were well versed in SQL, you would need a thorough understanding of our backend data model -- not just projects, tokens, etc, but how the django metadata relates to the actual SQL databases. 

So fine, we just post a clarity ingest script. Problem there is we don't have one for the new data format, and the old one won't work with the new ndstore branches. And, I've further confounded the issue because histogram ROI code only runs on microns, which doesn't run on dsp at the moment. 

Generating histograms for ROIs will be easy to add to reproducibility once I finish writing the code. So, there's a silver lining I suppose...

**Comment by jovo** [comment]
@alexbaden - please update paper with @willgray estiamtes.

for clarity, however, the answer is O(600),
it is just the ROIs.  although, that's per brain, and we have 15, so 15
times that i guess.

On Wed, Jun 15, 2016 at 11:20 PM, William Gray notifications@github.com
wrote:

> Sure - it's hard for me to estimate ramon objects without knowing all the
> underlying stuff.
> Also gives credit to image dataset rather than analysis people - maybe we
> just list multiple refs for each anno paper? Based on what I know as a
> first cut:
> - kasthuri machine - O(100000)
> - takemura machine - O(100000)
> - harris hand - O(1000)
> - vesicle (subset of kasthuri?) - O(100000)
> - dyer (xbrain? hand) - O(1000)
> - bhatla (worm, right?) - O(1000), to be confirmed
> - kutten (clarity mouse, right?) - O(10000), to be confirmed
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/61#issuecomment-226378587,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcl4-oopfnl3Im75COPSGVTo84R2gks5qMMD2gaJpZM4I06g4
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by jovo** [comment]
@alexbaden - i understand.  we'll deal with it, i'm not expecting it to go
in the submission anyway, only the revision, as discussed, so we'll have
time.

On Wed, Jun 15, 2016 at 11:22 PM, Alex Baden notifications@github.com
wrote:

> @jovo https://github.com/jovo For clarity reproducibility and histogram
> stuff, the clarity "ingest" I am doing is fundamentally not reproducible.
> I'm dumping brains from dsp in the old format, converting to the new format
> (manually, by disabling foreign key checks and running custom SQL queries),
> and re-loading the data to match our new channels format. Even if you were
> well versed in SQL, you would need a thorough understanding of our backend
> data model -- not just projects, tokens, etc, but how the django metadata
> relates to the actual SQL databases.
> 
> So fine, we just post a clarity ingest script. Problem there is we don't
> have one for the new data format, and the old one won't work with the new
> ndstore branches. And, I've further confounded the issue because histogram
> ROI code only runs on microns, which doesn't run on dsp at the moment.
> 
> Generating histograms for ROIs will be easy to add to reproducibility once
> I finish writing the code. So, there's a silver lining I suppose...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/61#issuecomment-226378829,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcmXaH_UgepWgO_W3FJZ5b_MaUx1gks5qMMGHgaJpZM4I06g4
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
@willgray The tokens for the annotation references are all in google sheets.

**Comment by wrgr** [comment]
i should explain - I chose to give powers of 10 estimates.  15 x 600 = 9000 ~ 10^4.  I can refine as we go, or improve our data sources.

Thanks!

**Comment by jovo** [comment]
ok, good enough for submission. let's close this subtask out by alex
updating the paper.

On Wed, Jun 15, 2016 at 11:25 PM, William Gray notifications@github.com
wrote:

> i should explain - I chose to give powers of 10 estimates. 15 x 600 = 9000
> ~ 10^4. I can refine as we go, or improve our data sources.
> 
> Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/61#issuecomment-226379155,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcrZjp__HpYnOhFDYNl8ZoqbouRB7ks5qMMI4gaJpZM4I06g4
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by alexbaden** [comment]
- [x] revise fig0 caption, channels --> servers, delete footnote
- [x] explain GV not using 0 cuboids in table 1 and table 2 caption
- [x] table 2: ramon, hand, machine

**Comment by alexbaden** [comment]
I rewrote histogram (2.1.7 microservices), 2.2.1 (ndviz), 2.2.2 (histogram explorer), and 2.2.3 (ndviz annotations) to be more in line with OCAR.

**Comment by jovo** [comment]
@alexbaden this is great! in general, we want the last sentence of every figure/table caption to be the take home message.  eg, "Other counts are approximate" is not that. i'll make a new issue to fix all figure captions.
