### ISSUE TITLE
hyperref doesn't work

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#66]
needs to be fixed prior to submission, but not sooner.

**Comment by jovo** [comment]
we want to make life as easy as possible for reviewers, so we _always_ submit the easiest possible version to read, and possibly also the one the journal requires.  this means _with_ hyperrefs.
but, it can be the last thing we do prior to submission.

**Comment by wrgr** [comment]
This was O(1 minute).  Done.
