### ISSUE TITLE
figure/table captions

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#69]
1. sentence 1: what is this figure showing
2. sentence 2-n-1: details, including defining all acronyms used in legend, table
3. sentence n: take home message, eg, "ND is way better than everything else in regards to X."
- [x] fig 1 👌 
- [ ] fig 2
- [x] fig 3 👌 
- [x] fig 4
- [ ] fig 5
- [x] fig 6
- [x] table 1 👌 
- [x] table 2 👌

**Comment by alexbaden** [comment]
I made a first pass at fig1, fig3, table1, and table2. 

@jovo / @willgray  can you fact check the table 1 caption claim? Do we need a citation, if it's true?

**Comment by jovo** [comment]
@alexbaden its true.  if somebody balks, we cite it.  i made minor modifications, in general however, it looks great.
