### ISSUE TITLE
Case Study 2 Complete

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#70]
Case study 2 is complete for initial submission.

Will continue to enumerate as we go:
- [ ] Reproducibility page for CS2
- [x] Explain/document/code for pipeline end to end (csv file and code in ndpaper
- [x] New figure showing maximum projections and spatial plot
- [x] Initial version of non-uniform stats 
- [x] Rewrite text so that it matches these results
- [x] Add a bit of distributed computing flavor
- [x] Hundreds of spot checks
### Other stuff
- [x] move master to gh-pages
- [x] ndstore will todos
- [x] assess cs1
- [x] fix remaining figure captions once we have figures

**Comment by wrgr** [comment]
Working through the data analysis and integrity checks.  Uncovered some biased classifier results in layer 1 - solving with outlier rejection and an improved masking strategy.

**Comment by wrgr** [comment]
Done!  And ready for review.  :)  Actions should go in a followup issue, to be addressed week of July 5th.  @jovo @j6k4m8 

w00t

**Comment by wrgr** [comment]
start here...everything is intergrated - reproducibility page has pointers to all the things:  https://github.com/neurodata/ndpaper/blob/gh-pages/spatialsynapses.md

**Comment by jovo** [comment]
amazeballs!!
ndpaper in overleaf is updated presumably, in addition to the gh-pages?

On Mon, Jun 27, 2016 at 8:24 PM, William Gray notifications@github.com
wrote:

> start here...everything is intergrated - reproducibility page has pointers
> to all the things:
> https://github.com/neurodata/ndpaper/blob/gh-pages/spatialsynapses.md
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/70#issuecomment-228914899,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjcsNQwdVEqSDYtwqeu8Ov10Yqmgy6ks5qQGmzgaJpZM4I5Sh4
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by wrgr** [comment]
yessir!  case study 2 is done (for the moment!)
