### ISSUE TITLE
Case 1:  Neurocartography

### ISSUE THREAD

**Issue by wrgr** [openconnectome/ocp-journal-paper#71]
### DoD for Case Study 1
- [ ] fix graphml files
- [x] make a table of results (fixing table 3 and renaming to neurocartography results)
- [x] fix text accordingly

**Comment by wrgr** [comment]
this is done for now.  all notebooks rerun and summary stats gathered.

**Comment by jovo** [comment]
fix graphml files?

**Comment by wrgr** [comment]
yea - moved to a new followup issue (https://github.com/neurodata/ndpaper/issues/72).  not sure what's wrong and internet is too terrible to generate atm.  but text and table are updated.
