### ISSUE TITLE
jovo feedback

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#76]
make a draft that you would be ok with putting on arxiv. below are more details
- [x] make it true. reading through the abstract, intro, etc., i notice a bunch of things that _could_ have been true, but are not.
- [x] we have 4 things: store, explore, analyze, model, make sure we are consistent throughout the text.
- [x] i updated fig0 in your lucidchart, better?
- [x] make sure each paragraph actually references a figure/table (not technically all paragraphs, but all paragraphs that should)
- [x] fix blatantly wrong grammar (like missing periods, etc.).
- [x] as i'm reading through text, i'm creating \todo's.  respond to them in text?
- [ ] we don't mention all the store usecases, in particular, public_tokens, and info, shouldn't we? if so, where?
- [ ] citations: make sure we cite all relevant background stuff, including CATMAID, ilastik, DVID if it exists, Keller Block Storage, Thunder.

**Comment by wrgr** [comment]
This is largely done, but continuing to make improvements through end of day from an "arxiv worthy" perspective.  Was lots to clean up...  :)

Ready to discuss in meetings though!

**Comment by jovo** [comment]
great, meaning i'll see you in an hour?

On Mon, Jul 11, 2016 at 7:07 AM, William Gray notifications@github.com
wrote:

> This is largely done, but continuing to make improvements through end of
> day from an "arxiv worthy" perspective. Was lots to clean up... :)
> 
> Ready to discuss in meetings though!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/neurodata/ndpaper/issues/76#issuecomment-231705598,
> or mute the thread
> https://github.com/notifications/unsubscribe/AACjct37YJhl1LgNfPSNI8MRJXVgs3Mmks5qUiP5gaJpZM4JEt9E
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
