### ISSUE TITLE
Table 1A

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#8]
meta-rows: publications
rows: _image_ tokens

columns:
- group name
- modality
- species 
- region
  (the above 3 are per _meta-row_)
- dataset name
- token 
- XYZT resolution
- XYZTC num pixels
- total size
- reference

please "highlight" (not sure what that means exactly) the bock11 & kasthuri15 datasets.

i recommend writing a function that crawls and gets all projinfo.json files for each token, and maybe even storing them locally (would be fine to store them all in this repo).

then, we can modify these tables without having to crawl OCP agin...

**Comment by j6k4m8** [comment]
With your clearance, I'm going to use [this](https://github.com/j6k4m8/PyTablePrinter) which I made mostly for this purpose. Abstracts away a lot of the dirty-work I've had to do to format these nicely

**Comment by jovo** [comment]
that's amazeballs.

On Tue, Dec 29, 2015 at 3:12 PM, Jordan Matelsky notifications@github.com
wrote:

> With your clearance, I'm going to use this
> https://github.com/j6k4m8/PyTablePrinter which I made mostly for this
> purpose. Abstracts away a lot of the dirty-work I've had to do to format
> these nicely
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/ocp-journal-paper/issues/8#issuecomment-167866748
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by jovo** [comment]
- [x] latin species name (eg. M. musculus, C. elegans)
- [x] consistent column title naming (eg, #voxels, #channels, #timesteps)
- [x] Reference should be `[<lastname of first author> et al. <journal> (<year>)](link)`, eg "Bock et al. Nature (2011)" 
  or something like that.  i made that up based on Nature's format.
- [x] freeman14 modality, not sure, what do you think? "Ophys"? "CI" for calcium imaging.  i am kinda leaning towards Ophys, because the services we build for Ophys should work for any Ophys, including voltage and calcium.
- [x] i don't think "Hz" goes in the freeman14 row, i think resolution says "(nm; Hz)", and then 650 x 650 x 5000; 0.8.  what do you think?
- [x] dataset is the _second_ column
- [x] reference is the _first_ column
- [x] add "size (GB)" column after #timesteps, where size=X_Y_Z_C_T
- [x] "Resolution (nm^3; Hz)"

**Comment by j6k4m8** [comment]
Agreed. Push coming up (eta 1m30s)

Do you know what the two unpopulated kasthuri tokens are called in the paper itself? (No mention of Maine, etc.) Still looking for their res

**Comment by jovo** [comment]
oh, they mention 3 different _resolutions_.
maine is the one that looks like the state of Maine, i think it is the coarsest resolution.
the other is the middle resolution.

**Comment by jovo** [comment]
- [x] "Dimensions" replaces #voxels, #channels, #timestesps, and is X x Y x Z x C x T 
- [X](ideally, those are times, not) 
- [x] add "Total (GV)" column after "Dimensions", where it is =X_Y_Z_C_T
- [x] "Resolution (nm^3; Hz)" (be consistent, semicolon or comma, in both header and each row)
- [x] kas size

do this, and we are done with this table, at least for now.

**Comment by j6k4m8** [comment]
@jovo think this is done, correct? Going to use this table's data to generate the new one, so want to confirm

**Comment by j6k4m8** [comment]
I think fixed by https://github.com/neurodata/weekly-status-reports/issues/28?

**Comment by jovo** [comment]
yes

On Wed, Mar 9, 2016 at 3:51 PM, Jordan Matelsky notifications@github.com
wrote:

> I think fixed by neurodata/weekly-status-reports#28
> https://github.com/neurodata/weekly-status-reports/issues/28?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/neurodata/ocp-journal-paper/issues/8#issuecomment-194502360
> .

## 

the glass is all full:  half water, half air.
neurodata.io
