### ISSUE TITLE
minor revisions

### ISSUE THREAD

**Issue by jovo** [openconnectome/ocp-journal-paper#80]
- [x] make sure each paragraph/subsection actually cites its corresponding figure panel, and states the "take home message"
- [x] make sure to cite figure panels consistently
- [x] add a "totals" row to table 1

**Comment by wrgr** [comment]
oh - thanks for these - if you get a second, point me to one you like and one you don't?  I thought we were already in good shape here.  Otherwise will figure it out.

**Comment by jovo** [comment]
one what?

**Comment by wrgr** [comment]
one reference you like and one you don't.  I thought I had squashed all these bugs - so maybe show me more what isn't gruntling you?

**Comment by jovo** [comment]
oh, reference,  some are literally "fig:blah-blah", ie, not even \ref{ } at all.
some use \ref{blah}(A), others \ref{blah}a, others bold, etc.
and sometimes, no explicit mention of the figure at all!

**Comment by wrgr** [comment]
ewww....ok.  on it.

**Comment by wrgr** [comment]
Believe this is fixed - there are a ton of these - if I missed any feel free to reopen!
